### PR TITLE
More books and commercial training

### PR DESCRIPTION
**Pull request by fommil**
continuing the trend of impartiality, additional training material has been added for both scalaz and cats.

### CODE REVIEW

**Comment by fosskers** [comment]
Thanks! I ended up reformatting it a bit.

**Comment by fommil** [comment]
cool :smile: although, as with all refactorings that do not have a test... a bug has crept in.

Functional Programming in Scala is for newcomers to Scala. FPMortals is for newcomers to FP (but with some Scala experience). The cats book is "an advanced" book.

**Comment by fosskers** [comment]
Ok, I'll rework the ScalaZ book descriptions. The Cats one self-described as asking for a year of Scala experience, so I parroted that.

**Comment by fommil** [comment]
I'm not sure `#fpmortals` needs a year of scala experience, but I think people should have at least read Martin Odersky's book or something of that equivalent. I assume knowledge of basic things but don't assume they understand `for` comprehensions, typeclasses, higher kinded types, or implicits. And I intentionally never mention or refer to Haskell!

**Comment by fosskers** [comment]
> And I intentionally never mention or refer to Haskell!

Blasphemy! :laughing: Says I, the Haskell guy. But I realize Haskell is a trigger word for some people, and your book is specifically targeting Java-background Scala people. Catering to an audience like that is totally fair - hell, I'd rather have people know and appreciate Monads without ever having heard of Haskell than the opposite.

**Comment by fommil** [comment]
My evil plan is to have an appendix section called "How to bluff Haskell at a conference" which will basically just show some basic Haskell syntax and refer back to things you learnt in the book.

https://www.youtube.com/watch?v=fULNUr0rvEc

**Pull request merged**
