### PR TITLE
optimising scalaz.Show[String]

### PR DESCRIPTION
**Pull request by fommil**
the evidence behind claims in https://github.com/scalaz/scalaz/pull/1549#issuecomment-349104185

### CODE REVIEW

**Comment by fommil** [comment]
btw, I do not think the comparison to stdlib or cats is fair in this example... they are [printing raw strings](https://github.com/typelevel/cats/blob/master/core/src/main/scala/cats/instances/string.scala) whereas scalaz is wrapping the string in quotes, making it possible to copy/paste back from the REPL, etc, and allowing for roundtripping via source code.

**Comment by fosskers** [comment]
I should add a note to the README about how the comparison isn't quite apples-to-apples. The same goes for the `Eq[List]` comparisons too, since that's `List` vs `IList`. Is there any reason why your `IList` improvements can't be ported to `List` too?

**Comment by fommil** [comment]
Maybe they can, but I'd rather optimise the preferred data structures rather than give people reasons not to switch.

**Comment by fosskers** [comment]
Fair.

**Comment by fosskers** [comment]
This has been taken care of in the latest Scalaz 7.2 versions.

**Pull request closed without merging**
